FROM gcr.io/distroless/static:nonroot

ARG TARGETOS
ARG TARGETARCH

WORKDIR /

# Copy pre-built provider binary
COPY _output/bin/${TARGETOS}_${TARGETARCH}/provider /usr/local/bin/provider

# Copy package metadata to root for Crossplane to find
COPY package/crossplane.yaml /package.yaml
COPY package/crds/*.yaml /crds/

USER 65532:65532
ENTRYPOINT ["/usr/local/bin/provider"]
