apiVersion: workers.cloudflare.m.crossplane.io/v1beta1
kind: KVNamespace
metadata:
  namespace: default
  name: example-kv-namespace
spec:
  forProvider:
    title: "my-application-data"
  providerConfigRef:
    name: default