apiVersion: dns.cloudflare.m.crossplane.io/v1beta1
kind: Record
metadata:
  name: apex
spec:
  forProvider:
    zoneSelector:
      matchLabels:
        identifier: dns-record
    name: crossplane
    content: 192.168.0.1
    proxied: false

  providerConfigRef:
    name: example
