apiVersion: firewall.cloudflare.m.crossplane.io/v1beta1
kind: Rule
metadata:
  name: challenge-wordpress-logins 
spec:
  forProvider:
    action: challenge
    description: Challenge wordpress login URLs
    priority: 1
    zoneRef:
      name: example
    filterRef:
      name: wordpress-logins
    
  providerConfigRef:
    name: example