apiVersion: workers.cloudflare.m.crossplane.io/v1beta1
kind: Script
metadata:
  name: edge-api-worker
  namespace: production
spec:
  forProvider:
    scriptName: "edge-api-worker"
    script: |
      export default {
        async fetch(request, env, ctx) {
          // Get the URL and parse it
          const url = new URL(request.url);

          // Add CORS headers
          const corsHeaders = {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type, Authorization',
          };

          // Handle preflight requests
          if (request.method === 'OPTIONS') {
            return new Response(null, {
              status: 200,
              headers: corsHeaders,
            });
          }

          // Simple API endpoint
          if (url.pathname === '/api/health') {
            return new Response(JSON.stringify({
              status: 'healthy',
              timestamp: new Date().toISOString(),
              worker: 'edge-api-worker'
            }), {
              headers: {
                'Content-Type': 'application/json',
                ...corsHeaders,
              },
            });
          }

          // Default response
          return new Response('Edge API Worker is running', {
            headers: corsHeaders,
          });
        },
      };
    module: true
    compatibilityDate: "2025-01-01"
    compatibilityFlags:
      - "streams_enable_constructors"
    usageModel: "bundled"
    bindings:
      - type: "kv_namespace"
        name: "CACHE_KV"
        namespaceId: "your-kv-namespace-id"
      - type: "json_data"
        name: "CONFIG"
        json: '{"environment": "production", "debug": false}'
    placement: "smart"
    logPush: true
    tags:
      - "api"
      - "edge"
      - "production"
  providerConfigRef:
    name: default